apiVersion: v1
kind: ServiceAccount
metadata:
 name: jenkins
 namespace: withserviceaccount
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: withserviceaccount
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""